In [5]:
import numpy as np
import random

In [6]:
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [34]:
arr1 = np.random.randint(4, 20, size=[3,3])
print(arr1)


even = arr1[arr1 % 2 == 0]
print(even)

[[10  5 15]
 [19 10 11]
 [ 4  4 16]]
[10 10  4  4 16]


In [26]:
original = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# original.shape
# original.reshape(1,9)
# original = original.flatten()

# original.shape

# print(original)

# print(original[::-1, ::-1])

# original[2][0]

# original[2,0]
#
# original[::2,::2]





In [32]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

c = a.min()

print(c)


1


In [35]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

c = a + b

print(c)

[ 6  8 10 12]
