NumPy Practice

In [2]:
import numpy as np

In [3]:

arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr2 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr3 = np.array([[[1, 4]], [[2, 5]], [[3, 6]]])

print(arr1.shape)
print(arr1.ndim)
print(arr2.shape)
print(arr2.ndim)
print(arr3.shape)
print(arr3.ndim)

(9,)
1
(3, 3)
2
(3, 1, 2)
3


In [3]:
zeroArr = np.zeros(10)
oneArr = np.ones(10)
fivesArr = np.full(10, 5)

concat = np.concatenate((zeroArr, oneArr, fivesArr))

print(concat)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [4]:
rangeArr = np.arange(10,51)
print(rangeArr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [5]:
dimRangeArr = np.arange(0,9).reshape(3, 3)

print(dimRangeArr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
print(arr1[:5])

[1 2 3 4 5]


In [7]:
print(arr2[:2, arr2.shape[1] - 2:])

[[2 3]
 [5 6]]


In [8]:
mask = arr1 > 5
print(mask)

print(arr1[mask])

[False False False False False  True  True  True  True]
[6 7 8 9]


In [9]:
a = np.array([5,24,82,5,34,4,18])
b = np.array([1,14,19,8,39,27,73])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)
print(b**2)

[  6  38 101  13  73  31  91]
[  4  10  63  -3  -5 -23 -55]
[   5  336 1558   40 1326  108 1314]
[5.         1.71428571 4.31578947 0.625      0.87179487 0.14814815
 0.24657534]
[  25  576 6724   25 1156   16  324]
[   1  196  361   64 1521  729 5329]


In [10]:
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m2 = np.array([[9,8,7],[6,5,4],[3,2,1]])
print(np.dot(m1, m2))

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [11]:
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([100, 200, 300, 400])

print(A+B)


[[101 202 303 404]
 [105 206 307 408]
 [109 210 311 412]]


In [12]:
randArr = np.array([2,54,23,42,12,3,69])
print(np.sum(randArr))
print(np.mean(randArr))
print(np.std(randArr))
print(np.median(randArr))

205
29.285714285714285
24.270583521823202
23.0


In [13]:
arr2D = np.array([[1, 2, 3],[24,21,12],[28,92,53]])
print(np.max(arr2D, axis = 1))
print(np.max(arr2D, axis = 0))


[ 3 24 92]
[28 92 53]


In [14]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y = x.reshape(3,4)
print(y)

w = y.flatten()
print(w)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [15]:
a = np.array([[1, 2]])
b = np.array([[3, 4]])

# Stack vertically (row-wise)
np.vstack((a, b))  # shape: (2, 2)

# Stack horizontally (column-wise)
np.hstack((a.T, b.T))  # shape: (2, 2)


array([[1, 3],
       [2, 4]])

In [16]:
import numpy as np

# Sorting a 1D array
arr_1d = np.array([3, 1, 4, 1, 5, 9, 2])
k = np.sort(arr_1d)
print(k)

# Sorting a 2D array along rows (axis=1)
arr_2d = np.array([[3, 2, 4], [5, 0, 1]])
p = np.sort(arr_2d, axis = 1)
print(p)

# Sorting a 2D array along columns (axis=0)
d = np.sort(arr_2d, axis = 0)
print(d)

# Sorting a 2D array as 1D flattened (None)
q = np.sort(arr_2d, axis = None)
print(q)



[1 1 2 3 4 5 9]
[[2 3 4]
 [0 1 5]]
[[3 0 1]
 [5 2 4]]
[0 1 2 3 4 5]


In [17]:
arr = np.array([30, 10, 20])

indices = np.argsort(arr)

print("Original:", arr)
print("Sorted indices:", indices)
print("Sorted array:", arr[indices])


Original: [30 10 20]
Sorted indices: [1 2 0]
Sorted array: [10 20 30]


In [18]:
a = np.arange(1,10)
print(a > 5)
print(a <= 3)

[False False False False False  True  True  True  True]
[ True  True  True False False False False False False]


In [19]:
b = np.arange(10,50)
print(np.logical_and(b > 20, b < 40))

[False False False False False False False False False False False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True False False False False False False
 False False False False]


In [20]:
c = np.array([5, 12, 17, 9, 3, 21, 19])
mask1 = c % 2 == 0
print(c[mask1])

mask2 = c > np.mean(c)
print(c[mask2])


[12]
[17 21 19]


In [21]:
d = np.array([10, 20, 30, 40, 50])
first = np.where(d > 30, 1, 0)
second = np.where(d < 25)
print(first)
print(second)

[0 0 0 1 1]
(array([0, 1]),)


In [22]:
e = np.array([2, 4, 6, 8, 10])

any = np.any(e>9)
print(any)

even = np.all(e%2 == 0)
print(even)

True
True


In [23]:
g = np.random.randint(1, 101, size=20)
mask = (g%3==0 ) & (g > 50)
print(np.sum(mask))

3


In [24]:
h = np.array([43, 23, 64, 21, 34, 19])
np.where(h < 30, -1, h)

array([43, -1, 64, -1, 34, -1])

In [25]:
i = np.random.randint(0, 20, size=(4,5))

mask3 = i > 10

mask4 = np.max(i, axis=1)

print(i[mask3])
print(mask4)
xyz = np.where(mask4>15)
print(mask4)
print(i[xyz])

[14 17 18 15 14 11 14 19 11 12]
[18 14 14 19]
[18 14 14 19]
[[14 17  6 18 15]
 [19 11 12  5  2]]


In [26]:
arr9 = np.arange(0, 10, 0.2)
print(arr9)
arr10 = np.linspace(0, 10, 50)
print(arr10)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.
 7.2 7.4 7.6 7.8 8.  8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [27]:


arr = np.array([10, 20, 30, 40, 50])

# Select elements at positions 0, 3, and 4
print(arr[[0, 3, 4]])  # → [10 40 50]


[10 40 50]


In [28]:
# From a 2D array of shape (3x3), pick out the diagonal elements using fancy indexing.

a = np.array([[11, 12, 13],
              [21, 22, 23],
              [31, 32, 33]])

ywb = [0, 1, 2]

print(a[ywb, ywb])

[11 22 33]


In [29]:
# Create an array of 10 random integers from 1 to 100. Get the 3 largest numbers using np.argsort()
# and fancy indexing.

arr = np.random.randint(1,100, size=10)
print(arr)

sortedInd = np.argsort(arr)
print(sortedInd)

print(arr[sortedInd[-3::]])



[40  5 24 19 17 29 23 89 61 24]
[1 4 3 6 2 9 5 0 8 7]
[40 61 89]


In [30]:
# given matrix, Use fancy indexing to extract: 12, 21, 33. Replace them with -1


a = np.array([[11, 12, 13],
              [21, 22, 23],
              [31, 32, 33]])

b = np.array([0, 1, 2])
c = np.array([1, 0, 2])
a[b, c] = -1

print(a)



[[11 -1 13]
 [-1 22 23]
 [31 32 -1]]


In [31]:


arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print(arr[1, 2:4])

[8 9]


In [32]:
np.arange(10,110,10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [33]:
x = np.zeros(10)
x.dtype

dtype('float64')

In [34]:
np.random.randint(1, 6, 10)

array([5, 4, 5, 1, 2, 5, 1, 5, 3, 5])

In [35]:
w = np.random.rand(10)
print(w)

[0.47306037 0.30587635 0.32909652 0.78260311 0.24576283 0.23190187
 0.06911005 0.12293769 0.67280839 0.73828726]


In [36]:
from numpy import random

x=random.randint(100, size=5)

print(x)


[42 54  8 82 68]


In [37]:
random.rand(5, 3, 2)

array([[[0.76741839, 0.35523271],
        [0.40896544, 0.97172638],
        [0.10215196, 0.74785403]],

       [[0.54083308, 0.63846179],
        [0.35469826, 0.83875697],
        [0.48829922, 0.978559  ]],

       [[0.35634685, 0.86244312],
        [0.16967638, 0.50325628],
        [0.69779178, 0.37363402]],

       [[0.27923988, 0.80700606],
        [0.22540767, 0.68286229],
        [0.98544272, 0.52562972]],

       [[0.14379776, 0.24025188],
        [0.19801593, 0.44438239],
        [0.94034058, 0.42002306]]])